version: '3.9'

services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: "./"
        target: "/app/"
