version: '3.9'

services:
  client:
    container_name: client
    image: node:20
    ports:
      - '3000:3000'
    working_dir: /app
    command: 'yarn dev'
    volumes:
      - type: bind
        source: './'
        target: '/app/'

volumes:
  client_volume:
    name: client-volume
