import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Hello() {

  const [text, setText] = useState<string>('')
  
  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_LAMBDA_API_URL}/api/hello`)
      .then(res => res.json())
      .then(data => setText(data.message))
  })

  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        { process.env.NEXT_PUBLIC_LAMBDA_API_URL }
        { text }
      </main>
    </>
  )
}
