AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  turnip

  Sample SAM Template for turnip

Globals:
  Function:
    Timeout: 60
    MemorySize: 256
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'*'"

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-image
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: stock_code
          AttributeType: S
      KeySchema:
        - AttributeName: stock_code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-dynamodb-table

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowS3Object
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${MyBucket}/*"
              - Sid: AllowS3List
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${MyBucket}"
              - Sid: AllowDynamoDBTable
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt MyDynamoDBTable.Arn
              - Sid: AllowCloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-hello
      PackageType: Image
      ImageConfig:
        Command: [ "app.lambdaHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/hello
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  GoodByeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-goodbye
      PackageType: Image
      ImageConfig:
        Command: [ "app.goodbyeHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  ListedInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-listed-info
      PackageType: Image
      ImageConfig:
        Command: [ "app.listed_info_handler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/listed_info
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  PricesDailyQuotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-prices-daily_quotes
      PackageType: Image
      ImageConfig:
        Command: [ "app.prices_daily_quotes_handler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/prices-daily_quotes
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  RefreshTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-refresh-token
      PackageType: Image
      ImageConfig:
        Command: [ "app.refresh_token_handler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/refresh-token
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-weather
      PackageType: Image
      ImageConfig:
        Command: [ "app.weather_handler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/weather
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  MyApiGateway:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
