AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  turnip

  Sample SAM Template for turnip

Globals:
  Function:
    Timeout: 300
    MemorySize: 256
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'*'"

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-s3-bucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  ListedInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Code
          AttributeType: S
      KeySchema:
        - AttributeName: Code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-listed-info

  PricesDailyQuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Code
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: Code
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-prices-daily-quotes

  FinsStatementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LocalCode
          AttributeType: S
        - AttributeName: DisclosedDate
          AttributeType: S
      KeySchema:
        - AttributeName: LocalCode
          KeyType: HASH
        - AttributeName: DisclosedDate
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-fins-statements

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowS3Object
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${MyBucket}/*"
              - Sid: AllowS3List
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${MyBucket}"
              - Sid: AllowListedInfoTable
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt ListedInfoTable.Arn
              - Sid: AllowPricesDailyQuotesTable
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt PricesDailyQuotesTable.Arn
              - Sid: AllowFinsStatementsTable
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt FinsStatementsTable.Arn
              - Sid: AllowCloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-hello
      Description: "`Hello World`を返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.lambdaHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/hello
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  BusinessDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-business-day
      Description: "営業日情報を返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.businessDayHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/business_day
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  BusinessDayUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-business-day-updater
      Description: "営業日情報を定期更新するAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "update.businessDayUpdateHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  InfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-info
      Description: "銘柄情報(単一)を返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.infoHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/info
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  ListedInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-listed-info
      Description: "銘柄情報(一覧)を返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.listedInfoHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/listed_info
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  PricesDailyQuotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-prices-daily_quotes
      Description: "株価四本値情報を返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.pricesDailyQuotesHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/prices-daily-quotes
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  FinsStatementsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-fins-statements
      Description: "財務情報を返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.finsStatementsHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/fins-statements
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  SlackNotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-slack-notify
      Description: "Slack通知を行うAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "update.slackNotifyHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  ScreenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-screener
      Description: "銘柄スクリーニング結果を返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.screenerHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      MemorySize: 10240
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/screener
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  TmpCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-tmp-code
      Description: "一時コードを返すAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.tmp_code_handler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/tmp_code
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  RefreshTokenUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-refresh-token-updater
      Description: "リフレッシュトークンを定期更新するAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "update.refreshTokenUpdateHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 days)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  IdTokenUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-id-token-updater
      Description: "IDトークンを定期更新するAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "update.idTokenUpdateHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: rate(20 hours)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  ListedInfoUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-listed-info-updater
      Description: "銘柄情報を定期更新するAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "update.listedInfoUpdateHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  PricesDailyQuotesUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-daily-quotes-updater
      Description: "株化四本値情報を定期更新するAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "update.pricesDailyQuotesUpdateHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  FinsStatementsUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-statements-updater
      Description: "財務情報を定期更新するAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "update.finsStatementsUpdateHandler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  MyApiGateway:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
