AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  turnip

  Sample SAM Template for turnip

Globals:
  Function:
    Timeout: 300
    MemorySize: 256
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'*'"

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-s3-bucket
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  ListedInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Code
          AttributeType: S
      KeySchema:
        - AttributeName: Code
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-listed-info

  PricesDailyQuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Code
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: Code
          KeyType: HASH
        - AttributeName: Date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-prices-daily-quotes

  FinsStatementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LocalCode
          AttributeType: S
        - AttributeName: DisclosedDate
          AttributeType: S
      KeySchema:
        - AttributeName: LocalCode
          KeyType: HASH
        - AttributeName: DisclosedDate
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${AWS::StackName}-fins-statements

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowS3Object
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${MyBucket}/*"
              - Sid: AllowS3List
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${MyBucket}"
              - Sid: AllowListedInfoTable
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt ListedInfoTable.Arn
              - Sid: AllowPricesDailyQuotesTable
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt PricesDailyQuotesTable.Arn
              - Sid: AllowFinsStatementsTable
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt FinsStatementsTable.Arn
              - Sid: AllowCloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lambda-api
      Description: "API Gatewayから呼び出されるLambda。"
      PackageType: Image
      ImageConfig:
        Command: [ "api.handler" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: any
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref MyBucket
          LISTED_INFO_DYNAMODB_TABLE_NAME: !Ref ListedInfoTable
          PRICES_DAILY_QUOTES_DYNAMODB_TABLE_NAME: !Ref PricesDailyQuotesTable
          FINS_STATEMENTS_DYNAMODB_TABLE_NAME: !Ref FinsStatementsTable
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

  DailyScheduledFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-daily-scheduled
      Description: "毎朝9時に実行されるAPI。"
      PackageType: Image
      ImageConfig:
        Command: [ "scheduled.dailyScheduled" ]
      Role: !GetAtt MyLambdaRole.Arn
      Architectures:
      - x86_64
      Events:
        MySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *)
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  MyApiGateway:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
