version: '3.8'
services:
  minio:
    container_name: 'aws-local-s3-server'
    image: minio/minio:RELEASE.2023-08-09T23-30-22Z
    command: ['server', '/data', '--console-address', ':9001']
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio-password
    ports:
      - '11000:9000'
      - '11001:9001'
    volumes:
      - ./minio_data:/data
    restart: unless-stopped
  mc:
    container_name: 'aws-local-s3-client'
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'minio-password'
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 minio minio-password;
      mc mb myminio/my-s3-bucket;
      mc cp ./init_data/* myminio/my-s3-bucket;
      "
    volumes:
      - ./s3_init_data:/init_data
