name: Check

on:
  push:
    branches:
      - 'main'
      - 'server/*'
      - 'client/*'
      - 'common/*'
      - 'hotfix'
      - 'refactoring'
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - 'main'
      - 'server/*'
      - 'client/*'
      - 'common/*'
      - 'hotfix'
      - 'refactoring'
      - 'feature/*'
      - 'bugfix/*'

env:
  client-directory: ./client
  server-directory: ./server
  node-version: 18

jobs:
  lambda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.server-directory }}/src
      - name: Lint
        run: yarn lint
        working-directory: ${{ env.server-directory }}/src
      - name: Prettier
        run: yarn prettier:check
        working-directory: ${{ env.server-directory }}/src
      - name: Test
        run: yarn test
        working-directory: ${{ env.server-directory }}/src
  nextjs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.client-directory }}
      - name: Lint
        run: yarn lint
        working-directory: ${{ env.client-directory }}
      - name: Prettier
        run: yarn prettier:check
        working-directory: ${{ env.client-directory }}
      - name: Test
        run: yarn test
        working-directory: ${{ env.client-directory }}
