name: ci

on:
  pull_request:
    branches:
      - 'main'
      - 'staging/*'
      - 'server/*'
      - 'client/*'
      - 'common/*'
      - 'hotfix'

jobs:
  lambda-check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./server/src/
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules-server
        with:
          path: 'server/**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('server/**/yarn.lock') }}
      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Vulnerability check
        run: yarn audit
      # - name: Deprication check
      #   run: yarn outdated
  nextjs-check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./client/
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules-client
        with:
          path: 'client/**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('client/**/yarn.lock') }}
      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Vulnerability check
        run: yarn audit
      # - name: Deprication check
      #   run: yarn outdated
