name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  project-name: ${{ secrets.PROJECT_NAME }}
  client-directory: ./client
  server-directory: ./server
  node-version: 18

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  lambda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.server-directory }}/src
      - name: Lint
        run: yarn lint
        working-directory: ${{ env.server-directory }}/src
      - name: Prettier
        run: yarn prettier:check
        working-directory: ${{ env.server-directory }}/src
      - name: Test
        run: yarn test
        working-directory: ${{ env.server-directory }}/src
      - name: Vulnerability check
        run: yarn audit
        working-directory: ${{ env.server-directory }}/src
      - name: Deprication check
        run: yarn outdated
        working-directory: ${{ env.server-directory }}/src
  lambda-deploy:
    runs-on: ubuntu-latest
    needs: lambda-check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create dotenv file
        run: echo $'${{ secrets.LAMBDA_DOTENV }}' > ./src/.env
        working-directory: ${{ env.server-directory }}
      - name: Add Data to dotenv file
        run: |
          echo "ENVIRONMENT=production" >> ./src/.env
          echo "S3_BUCKET_NAME=${{ env.project-name }}-production-s3-bucket" >> ./src/.env
          echo "LISTED_INFO_DYNAMODB_TABLE_NAME=${{ env.project-name }}-production-listed-info" >> ./src/.env
          echo "PRICES_DAILY_QUOTES_DYNAMODB_TABLE_NAME=${{ env.project-name }}-production-prices-daily-quotes" >> ./src/.env
          echo "FINS_STATEMENTS_DYNAMODB_TABLE_NAME=${{ env.project-name }}-production-fins-statements" >> ./src/.env
        working-directory: ${{ env.server-directory }}
      - run: sam build --use-container
        working-directory: ${{ env.server-directory }}
      - name: Deploy Lambda
        run: sam deploy --stack-name ${{ env.project-name }}-production
        working-directory: ${{ env.server-directory }}
  nextjs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.client-directory }}
      - name: Lint
        run: yarn lint
        working-directory: ${{ env.client-directory }}
      - name: Prettier
        run: yarn prettier:check
        working-directory: ${{ env.client-directory }}
      - name: Test
        run: yarn test
        working-directory: ${{ env.client-directory }}
      - name: Vulnerability check
        run: yarn audit
        working-directory: ${{ env.client-directory }}
      - name: Deprication check
        run: yarn outdated
        working-directory: ${{ env.client-directory }}
  nextjs-build:
    needs:
      - nextjs-check
      - lambda-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Get API Gateway URL
        run: |
          API_GATEWAY_URL=$(aws cloudformation describe-stacks --stack-name ${{ env.project-name }}-production --query "Stacks[0].Outputs[?OutputKey=='MyApiGateway'].OutputValue" --output text --no-cli-pager)
          echo "API_GATEWAY_URL=$API_GATEWAY_URL" >> $GITHUB_ENV
      - name: API Gateway URL empty guard
        run: |
          echo "API Gateway URL -> ${{ env.API_GATEWAY_URL }}"
          if [ -z "${{ env.API_GATEWAY_URL }}" ]; then
            echo "API Gateway URL is empty"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          static_site_generator: next
      - name: Install dependencies
        run: yarn install # --production --frozen-lockfile
        working-directory: ${{ env.client-directory }}
        # env:
        #   NODE_ENV: production
      - name: Generating .env.local
        run: |
          echo "${{ secrets.NEXTJS_ENV_LOCAL }}" > .env.local
      - name: Check status code of curl response
        env:
          api-gateway-url: ${{ env.API_GATEWAY_URL }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.API_GATEWAY_URL }}/api/hello")
          if [ $response -eq 200 ]; then
            echo "Success"
          else
            echo "Failed"
            echo "Response code: $response"
            echo "API Gateway URL: ${{ env.API_GATEWAY_URL }}"
            exit 1
          fi
      - name: Set API Gateway URL
        run: echo "NEXT_PUBLIC_LAMBDA_API_URL=${{ env.API_GATEWAY_URL }}" >> .env.local
        working-directory: ${{ env.client-directory }}
      - name: Cat .env.local
        run: cat .env.local
        working-directory: ${{ env.client-directory }}
      - name: Build with Next.js
        run: yarn build
        # env:
        #   NODE_ENV: production
        working-directory: ${{ env.client-directory }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.client-directory }}/dist
  nextjs-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: nextjs-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
